apiVersion: v1
kind: Service
metadata:
  name: {{ include "jambonchess.fullname" . }}-socket
  labels:
    {{- include "jambonchess.labels" . | nindent 4 }}
spec:
  type: {{ .Values.socket.service.type }}
  ports:
    - port: {{ .Values.socket.service.port }}
      targetPort: {{ .Values.socket.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "jambonchess.selectorLabels" . | nindent 4 }}
